<div class="linhaprincipal">
    INSERIR BOTAO DO FORMULARIO PARA VINCULO
    DO FORNECEDOR - PRODUTO

     1 PRODUTO PODE TER VARIOS FORNECEDORES.
     1 FORNECEDOR PODE FORNECER VARIOS PRODUTOS. 
</div>
